[package]
name = "xhs_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
reqwest = "0.11.23"
scraper = "0.18.0"
tokio = { version = "1.35.1", features = ["full"] }
